[32m2024-10-08 09:42:01 +0200[0m - dagster - [34mDEBUG[0m - __ASSET_JOB_1 - 273ea3b8-899b-42ce-94c5-d4673bc23633 - 109717 - LOGS_CAPTURED - Started capturing logs in process (pid: 109717).
[32m2024-10-08 09:42:01 +0200[0m - dagster - [34mDEBUG[0m - __ASSET_JOB_1 - 273ea3b8-899b-42ce-94c5-d4673bc23633 - 109717 - dbt_analytics - STEP_START - Started execution of step "dbt_analytics".
[32m2024-10-08 09:42:01 +0200[0m - dagster - [34mINFO[0m - __ASSET_JOB_1 - 273ea3b8-899b-42ce-94c5-d4673bc23633 - dbt_analytics - A dbt subsetted execution is being performed. Overriding default dbt selection arguments `['--select', 'fqn:*', '--exclude', 'config.materialized:incremental']` with arguments: `['analytics.staging.stg_zones']`.
[32m2024-10-08 09:42:02 +0200[0m - dagster - [34mINFO[0m - __ASSET_JOB_1 - 273ea3b8-899b-42ce-94c5-d4673bc23633 - dbt_analytics - Copying `/home/me/dagster_dbt_tutorial/dagster-and-dbt/analytics/target/partial_parse.msgpack` to `/home/me/dagster_dbt_tutorial/dagster-and-dbt/analytics/target/dbt_analytics-273ea3b-07cf342/partial_parse.msgpack` to take advantage of partial parsing.
[32m2024-10-08 09:42:02 +0200[0m - dagster - [34mINFO[0m - __ASSET_JOB_1 - 273ea3b8-899b-42ce-94c5-d4673bc23633 - dbt_analytics - Running dbt command: `dbt build --select analytics.staging.stg_zones`.
[32m2024-10-08 09:42:05 +0200[0m - dagster - [34mINFO[0m - __ASSET_JOB_1 - 273ea3b8-899b-42ce-94c5-d4673bc23633 - dbt_analytics - Finished dbt command: `dbt build --select analytics.staging.stg_zones`.
[32m2024-10-08 09:42:05 +0200[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB_1 - 273ea3b8-899b-42ce-94c5-d4673bc23633 - 109717 - dbt_analytics - STEP_FAILURE - Execution of step "dbt_analytics" failed.

dagster_dbt.errors.DagsterDbtCliRuntimeError: The dbt CLI process with command

`dbt build --select analytics.staging.stg_zones`

failed with exit code `2`. Check the stdout in the Dagster compute logs for the full information about the error, or view the dbt debug log: /home/me/dagster_dbt_tutorial/dagster-and-dbt/analytics/target/dbt_analytics-273ea3b-07cf342/dbt.log.

Errors parsed from dbt logs:

Encountered an error:
Runtime Error
  IO Error: Could not set lock on file "/home/me/dagster_dbt_tutorial/dagster-and-dbt/analytics/../data/staging/data.duckdb": Conflicting lock is held in /home/me/miniconda3/bin/python3.12 (PID 108687). See also https://duckdb.org/docs/connect/concurrency

Stack Trace:
  File "/home/me/dagster_dbt_tutorial/dagster_dbt_tut_env/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_plan.py", line 282, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/home/me/dagster_dbt_tutorial/dagster_dbt_tut_env/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 494, in core_dagster_event_sequence_for_step
    for user_event in _step_output_error_checked_user_event_sequence(
  File "/home/me/dagster_dbt_tutorial/dagster_dbt_tut_env/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 183, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
  File "/home/me/dagster_dbt_tutorial/dagster_dbt_tut_env/lib/python3.12/site-packages/dagster/_core/execution/plan/execute_step.py", line 88, in _process_asset_results_to_events
    for user_event in user_event_sequence:
  File "/home/me/dagster_dbt_tutorial/dagster_dbt_tut_env/lib/python3.12/site-packages/dagster/_core/execution/plan/compute.py", line 198, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn, compute_context):
  File "/home/me/dagster_dbt_tutorial/dagster_dbt_tut_env/lib/python3.12/site-packages/dagster/_core/execution/plan/compute.py", line 167, in _yield_compute_results
    for event in iterate_with_context(
  File "/home/me/dagster_dbt_tutorial/dagster_dbt_tut_env/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 473, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/home/me/dagster_dbt_tutorial/dagster-and-dbt/dagster_university/assets/dbt.py", line 28, in dbt_analytics
    yield from dbt.cli(["build"], context=context).stream()
  File "/home/me/dagster_dbt_tutorial/dagster_dbt_tut_env/lib/python3.12/site-packages/dagster_dbt/core/resources_v2.py", line 1147, in __next__
    return next(self._inner_iterator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/dagster_dbt_tutorial/dagster_dbt_tut_env/lib/python3.12/site-packages/dagster_dbt/core/resources_v2.py", line 619, in _stream_asset_events
    for event in self.stream_raw_events():
  File "/home/me/dagster_dbt_tutorial/dagster_dbt_tut_env/lib/python3.12/site-packages/dagster_dbt/core/resources_v2.py", line 712, in stream_raw_events
    self._raise_on_error()
  File "/home/me/dagster_dbt_tutorial/dagster_dbt_tut_env/lib/python3.12/site-packages/dagster_dbt/core/resources_v2.py", line 804, in _raise_on_error
    raise error
[0m
